security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_auth
                check_path: app_auth
                username_parameter: _username
                password_parameter: _password
                default_target_path: products  # ✅ redirection après login

            logout:
                path: app_logout
                target: app_auth

    access_control:
        - { path: ^/profile, roles: ROLE_USER }